name             'was'
maintainer       'IBM Corp'
maintainer_email ''
license 'Copyright IBM Corp. 2016, 2017'
description      'Installs and configures WebSphere Application Server and WebSphere Application Server Network Deployment'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))

version '0.1.47'

depends          'ibm_cloud_utils'
depends          'im'
depends          'linux'
supports 'RHEL6', '>= 6.5'
supports 'RHEL7', '>= 7.0'
supports 'Ubuntu14', '>= 14.04'
supports 'Ubuntu16', '>= 16.0.4' 
attribute 'was/config/enable_admin_security',
          :default => 'true',
          :description => 'Enable WebSphere administrative console security',
          :displayname => 'Enable administrative security',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/config/os_service',
          :default => 'true',
          :description => 'Setup appropriate operating system job to start WebSphere at system startup',
          :displayname => 'Enable automatic starting of WebSphere servers',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/config/use_default_certs',
          :default => 'true',
          :description => 'Use WebSphere default certificates when creating profiles',
          :displayname => 'Create a new default personal certificate',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/dmgr_host_name',
          :default => '',
          :description => 'The fully qualified domain name of the deployment manager to federate this node to',
          :displayname => 'Deployment manager hostname',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/dmgr_role_name',
          :default => '',
          :description => 'Used for Chef search',
          :displayname => 'dmgr_role_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/edition/base',
          :default => 'false',
          :description => 'WebSphere Application Server will be installed and configured',
          :displayname => 'WebSphere base edition',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/edition/nd',
          :default => 'true',
          :description => 'WebSphere Application Server Network Deployment will be installed and configured',
          :displayname => 'WebSphere nd edition',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/features/core.feature',
          :default => 'true',
          :description => 'Indicates that the application server feature (core.feature) should be installed',
          :displayname => 'Install WebSphere runtime',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/features/ejbdeploy',
          :default => 'true',
          :description => 'Indicates whether the optional feature EJBDeploy tool for pre-EJB 3.0 modules should be installed',
          :displayname => 'Install optional EJBDeploy feature',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/features/embeddablecontainer',
          :default => 'true',
          :description => 'Indicates whether the embeddable EJB container should be installed',
          :displayname => 'Install optional Embeddable EJB Container feature',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/features/liberty',
          :default => 'false',
          :description => 'Indicates whether the WebSphere Liberty Application Server should be installed. Used for WebSphere installations that bundled Liberty as an install option',
          :displayname => 'WebSphere features liberty',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/features/samples',
          :default => 'false',
          :description => 'Indicates whether the PlantsByWebSphere sample application should be installed',
          :displayname => 'Install optional WebSphere Sample applications',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/features/thinclient',
          :default => 'true',
          :description => 'Indicates whether the optional IBM stand-alone thin clients and resource adapters should be installed',
          :displayname => 'Install optional stand-alone thin clients and resource adapters',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/ihs_host_name',
          :default => '',
          :description => 'Fully qualified domain name of the IBM HTTP server',
          :displayname => 'IBM HTTP hostname',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/ihs_role_names',
          :default => '',
          :description => 'Used for Chef search',
          :displayname => 'ihs_role_names',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'array'
attribute 'was/install_dir',
          :default => '/opt/IBM/WebSphere/AppServer',
          :description => 'The installation root directory for the WebSphere Application Server product binaries',
          :displayname => 'WebSphere product installation directory',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/java_features/websphere_java_v8/enable',
          :default => 'true',
          :description => 'Installation Manager response file option to install Java 8 SDK. Valid only for WebSphere V9',
          :displayname => 'Install Java 8 SDK',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/java_features/websphere_java_v8/offering_id',
          :default => 'com.ibm.java.jdk.v8',
          :description => 'Java SDK installation manager offering ID value',
          :displayname => 'Java 8 SDK installation manager offering id',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/java_version',
          :default => '8.0.4.70',
          :description => 'The Java SDK version that should be installed with the WebSphere Application Server. Example format is 8.0.4.70',
          :displayname => 'Java SDK version',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_perms',
          :default => '750',
          :description => 'File permissions for the WebSphere installation',
          :displayname => 'WebSphere Operating System permissions',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/comment',
          :default => 'WAS administrative user',
          :description => 'Comment that will be added when creating the userid',
          :displayname => 'Add comment for the user',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/gid',
          :default => 'wasgrp',
          :description => 'Operating System group name that will be assigned to the product installation',
          :displayname => 'WebSphere User Group Name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/home',
          :default => '/home/wasadmin',
          :description => 'Home directory location for operating system user that is used for product installation',
          :displayname => 'WebSphere System Installation Userid Home Directory',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/ldap_user',
          :default => 'false',
          :description => 'Use LDAP to authenticate operating system account on Linux logins',
          :displayname => 'Use LDAP for Authentication',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/name',
          :default => 'wasadmin',
          :description => 'Operating system userid that will be used to install the product. Userid will be created if it does not exist',
          :displayname => 'WebSphere Installation Userid',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/shell',
          :default => '/bin/bash',
          :description => 'Default shell for the operating system userid',
          :displayname => 'WebSphere System Userid Default Shell',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profile_dir',
          :default => '/opt/IBM/WebSphere/AppServer/profiles',
          :description => 'The directory path that contains WebSphere Application Server profiles',
          :displayname => 'WebSphere configuration data location',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/cell',
          :default => 'cell01',
          :description => 'A cell name is a logical name for the group of nodes administered by the deployment manager cell',
          :displayname => 'Cell name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/host',
          :default => '',
          :description => 'A host name is the domain name system (DNS) name (short or long) or the IP address of this virtual machine and cannot contain an understore (_)',
          :displayname => 'Deployment manager host name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/keystorepassword',
          :default => '',
          :description => 'Specifies the password to use on keystore created during profile creation',
          :displayname => 'Default keystore password',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/node',
          :default => '{SHORTHOSTNAME}CellManager01',
          :description => 'A node name is for administration by the deployment manager.  The name must be unique within the cell',
          :displayname => 'Node name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/personalcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the personal certificate that you are creating when you create the profile',
          :displayname => 'Personal certificate Distingushed name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/personalcertvalidityperiod',
          :default => '3',
          :description => 'An optional parameter that specifies the amount of time in years that the default personal certificate is valid',
          :displayname => 'Personal certificate expiration period in years',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/BOOTSTRAP_ADDRESS',
          :default => '9809',
          :description => 'Deployment manager bootstrap port value (BOOTSTRAP_ADDRESS)',
          :displayname => 'Bootstrap Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/CELL_DISCOVERY_ADDRESS',
          :default => '7277',
          :description => 'Deployment manager Cell Discovery Address port value (CELL_DISCOVERY_ADDRESS)',
          :displayname => 'Cell Discovery Address',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9402',
          :description => 'Deployment manager CSIV2 Client Authentication Listener Port (CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS)',
          :displayname => 'CSIV2 Client Authentication Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9403',
          :description => 'Deployment manager CSIV2 Server Authentication Listener Port (CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS) port value',
          :displayname => 'CSIV2 Server Authentication Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/DCS_UNICAST_ADDRESS',
          :default => '9352',
          :description => 'Deployment manager High Availability Manager Communication Port (DCS_UNICAST_ADDRESS)',
          :displayname => 'High Availability Manager Communication Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/DataPowerMgr_inbound_secure',
          :default => '5555',
          :description => 'Deployment manager DataPower Appliance Manager Secure Inbound Port (DataPowerMgr_inbound_secure)',
          :displayname => 'DataPower Appliance Manager Secure Inbound Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/IPC_CONNECTOR_ADDRESS',
          :default => '9632',
          :description => 'Deployment manager IPC Connector Port value (IPC_CONNECTOR_ADDRESS)',
          :displayname => 'IPC Connector Port value',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/ORB_LISTENER_ADDRESS',
          :default => '9100',
          :description => 'Deployment manager ORB Listener Port (ORB_LISTENER_ADDRESS)',
          :displayname => 'ORB Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/OVERLAY_TCP_LISTENER_ADDRESS',
          :default => '11006',
          :description => 'Deployment manager Administration Overlay TCP Port (OVERLAY_TCP_LISTENER_ADDRESS)',
          :displayname => 'Administration Overlay TCP Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/OVERLAY_UDP_LISTENER_ADDRESS',
          :default => '11005',
          :description => 'Deployment manager Administration Overlay UDP Port (OVERLAY_UDP_LISTENER_ADDRESS)',
          :displayname => 'Administration Overlay UDP Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9401',
          :description => 'Deployment manager SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'SAS_SSL_SERVERAUTH_LISTENER_ADDRESS Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8879',
          :description => 'Deployment manager SOAP connector port value (SOAP_CONNECTOR_ADDRESS)',
          :displayname => 'SOAP Connector Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/STATUS_LISTENER_ADDRESS',
          :default => '9420',
          :description => 'Deployment manager Status Update Listener Port (STATUS_LISTENER_ADDRESS)',
          :displayname => 'Status Update Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/WC_adminhost',
          :default => '9060',
          :description => 'Deployment manager administrative console port (WC_adminhost)',
          :displayname => 'Administrative Console Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/WC_adminhost_secure',
          :default => '9043',
          :description => 'Deployment manager adminsitrative secure console port (WC_adminhost_secure)',
          :displayname => 'Administrative Console Secure Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/XDAGENT_PORT',
          :default => '7060',
          :description => 'Deployment manager Middleware Agent RPC port (XDAGENT_PORT)',
          :displayname => 'Middleware Agent RPC port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/profile',
          :default => 'Dmgr01',
          :description => 'Deployment manager profile name',
          :displayname => 'Profile name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/signingcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the root signing certificate that you create when you create the profile',
          :displayname => 'Root certificate distinguished name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/signingcertvalidityperiod',
          :default => '15',
          :description => 'An optional parameter that specifies the amount of time in years that the root signing certificate is valid',
          :displayname => 'Root signing certificate expiration period in years',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/cell',
          :default => 'cell01',
          :description => 'Cell name of the Job manager ',
          :displayname => 'Job Manager cell name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/host',
          :default => '{FULLHOSTNAME}',
          :description => 'A host name is the domain name system (DNS) name (short or long) or the IP address of this virtual machine and cannot contain an understore (_)',
          :displayname => 'Job Manager host name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/keystorepassword',
          :default => '',
          :description => 'Specifies the password to use on all keystore files created during profile creation',
          :displayname => 'Default keystore password',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/node',
          :default => '{SHORTHOSTNAME}JobMgr01',
          :description => 'Node name is for administration and must be unique',
          :displayname => 'Job Manager node name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/personalcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the personal certificate that you are creating when you create the profile',
          :displayname => 'Personal certificate Distingushed name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/personalcertvalidityperiod',
          :default => '3',
          :description => 'An optional parameter that specifies the amount of time in years that the default personal certificate is valid',
          :displayname => 'Personal certificate expiration period in years',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/BOOTSTRAP_ADDRESS',
          :default => '9808',
          :description => 'Bootstrap port value (BOOTSTRAP_ADDRESS)',
          :displayname => 'Job Manager Bootstrap address',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9402',
          :description => 'CSIV2 Client Authentication Listener Port (CSIV2_ SSL_ MUTUALAUTH_ LISTENER_ ADDRESS)	9402',
          :displayname => 'Job Manager CSIV2 Client Authentication Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9403',
          :description => 'CSIV2 Server Authentication Listener Port (CSIV2_ SSL_ SERVERAUTH_ LISTENER_ ADDRESS)',
          :displayname => 'Job Manager CSIV2 Server Authentication Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/IPC_CONNECTOR_ADDRESS',
          :description => 'IPC Connector Port value (IPC_CONNECTOR_ADDRESS),
# <md>          :type => ',
          :displayname => 'Job Manager IPC Connector Port value'
attribute 'was/profiles/job_manager/ports/ORB_LISTENER_ADDRESS',
          :default => '9099',
          :description => 'ORB Listener Port (ORB_LISTENER_ADDRESS)',
          :displayname => 'Job Manager ORB listener port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9401',
          :description => 'SAS_ SSL_ SERVERAUTH_ LISTENER_ ADDRESS (Deprecated)',
          :displayname => 'Job Manager SAS SSL ServerAuth port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8876',
          :description => 'SOAP connector port value (SOAP_CONNECTOR_ADDRESS)',
          :displayname => 'Job Manager',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/STATUS_LISTENER_ADDRESS',
          :default => '9425',
          :description => 'Status Update Listener Port (STATUS_ LISTENER_ ADDRESS)',
          :displayname => 'Job Manager Status update listener port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/WC_adminhost',
          :default => '9960',
          :description => 'Job Manager administrative console port (WC_adminhost)',
          :displayname => 'Administrative Console Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/WC_adminhost_secure',
          :default => '9943',
          :description => 'Job Manager adminsitrative secure console port (WC_adminhost_secure)',
          :displayname => 'Administrative Console Secure Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/profile',
          :default => 'JobMgr01',
          :description => 'Job Manager profile name',
          :displayname => 'Job manager Profile name ',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/signingcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the root signing certificate that you create when you create the profile',
          :displayname => 'Root certificate distinguished name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/signingcertvalidityperiod',
          :default => '15',
          :description => 'An optional parameter that specifies the amount of time in years that the root signing certificate is valid',
          :displayname => 'Root signing certificate expiration period in years',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/dmgr_host',
          :default => '',
          :description => 'Speicfy the host name or IP address for an existing deployment manager',
          :displayname => 'Deployment manager host name or IP address',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/dmgr_port',
          :default => '',
          :description => 'Deployment manager SOAP port that is used when federating the custom profile',
          :displayname => 'Deployment manager SOAP port number',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/host',
          :description => 'A host name is the domain name system (DNS) name (short or long) or the IP address of this virtual machine and cannot contain an understore (_),
# <md>          :type => ',
          :displayname => 'Custom profile host name'
attribute 'was/profiles/node_profile/keystorepassword',
          :default => '',
          :description => 'Specifies the password to use on all keystore files created during profile creation',
          :displayname => 'Default keystore password',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/node',
          :default => '{SHORTHOSTNAME}Node01',
          :description => 'Unique node name for this federated node.  Must be unique within the cell',
          :displayname => 'Custom profile Node name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/personalcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the personal certificate that you are creating when you create the profile',
          :displayname => 'Personal certificate Distingushed name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/personalcertvalidityperiod',
          :default => '3',
          :description => 'An optional parameter that specifies the amount of time in years that the default personal certificate is valid',
          :displayname => 'Personal certificate expiration period in years',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/BOOTSTRAP_ADDRESS',
          :default => '2810',
          :description => 'Server bootstrap (BOOTSTRAP_ADDRESS)',
          :displayname => 'Bootstrap Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9202',
          :description => 'CSIV2 Client Authentication Listener Port (CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS)',
          :displayname => 'CSIV2 Client Authentication Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9201',
          :description => 'CSIV2 Server Authentication Listener Port (CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS)',
          :displayname => 'CSIV2 Server Authentication Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/DCS_UNICAST_ADDRESS',
          :default => '9354',
          :description => 'High Availability Manager Communication Port (DCS_UNICAST_ADDRESS)',
          :displayname => 'High availability manager communication port (DCS)',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/IPC_CONNECTOR_ADDRESS',
          :default => '9626',
          :description => 'IPC Connector Port value (IPC_CONNECTOR_ADDRESS)',
          :displayname => 'IPC Connector Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/NODE_DISCOVERY_ADDRESS',
          :default => '7272',
          :description => 'Node Discovery Address (NODE_DISCOVERY_ADDRESS)',
          :displayname => 'Node discovery address',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/NODE_IPV6_MULTICAST_DISCOVERY_ADDRESS',
          :default => '5001',
          :description => 'Node IPV6 Discovery Address (NODE_IPV6_MULTICAST_DISCOVERY_ADDRESS)',
          :displayname => 'Node IPV6 Discovery Address port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/NODE_MULTICAST_DISCOVERY_ADDRESS',
          :default => '5000',
          :description => 'was node_profile profiles ports NODE_MULTICAST_DISCOVERY_ADDRESS',
          :displayname => 'was node_profile profiles ports NODE_MULTICAST_DISCOVERY_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/ORB_LISTENER_ADDRESS',
          :default => '9101',
          :description => 'ORB Listener Port (ORB_LISTENER_ADDRESS)',
          :displayname => 'ORB Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/OVERLAY_TCP_LISTENER_ADDRESS',
          :default => '11002',
          :description => 'Node Administration Overlay TCP Port (OVERLAY_TCP_LISTENER_ADDRESS)',
          :displayname => 'Node Administration Overlay TCP Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/OVERLAY_UDP_LISTENER_ADDRESS',
          :default => '11001',
          :description => 'Node Administration Overlay UDP Port (OVERLAY_UDP_LISTENER_ADDRESS)',
          :displayname => 'Node Administration Overlay UDP Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9901',
          :description => 'was node_profile profiles ports SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'SAS_SSL_SERVERAUTH_LISTENER_ADDRESS Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8878',
          :description => 'SOAP connector port value (SOAP_CONNECTOR_ADDRESS)',
          :displayname => 'SOAP Connector Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/STATUS_LISTENER_ADDRESS',
          :default => '9420',
          :description => 'Status Update Listener Port (STATUS_LISTENER_ADDRESS)',
          :displayname => 'Status Update Listener port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/WC_adminhost',
          :default => '9060',
          :description => 'Administrative console port (WC_adminhost)',
          :displayname => 'Administrative Console Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/XDAGENT_PORT',
          :default => '7061',
          :description => 'Node Middleware Agent RPC port (XDAGENT_PORT)',
          :displayname => 'Node Middleware Agent RPC port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/profile',
          :default => 'Custom01',
          :description => 'Profile name for a custom profile',
          :displayname => 'Custom profile name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/signingcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the root signing certificate that you create when you create the profile',
          :displayname => 'Root certificate distinguished name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/signingcertvalidityperiod',
          :default => '15',
          :description => 'An optional parameter that specifies the amount of time in years that the root signing certificate is valid',
          :displayname => 'Root signing certificate expiration period in years',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/cell',
          :default => 'cell01',
          :description => 'Cell name for the application server',
          :displayname => 'Application server cell name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/host',
          :default => '{FULLHOSTNAME}',
          :description => 'A host name is the domain name system (DNS) name (short or long) or the IP address of this virtual machine and cannot contain an understore (_)',
          :displayname => 'Application server host name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/keystorepassword',
          :default => '',
          :description => 'Specifies the password to use on all keystore files created during profile creation',
          :displayname => 'Default keystore password',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/node',
          :default => '{SHORTHOSTNAME}Node01',
          :description => 'A node name is used for administration',
          :displayname => 'Application server node name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/personalcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the personal certificate that you are creating when you create the profile',
          :displayname => 'Personal certificate Distingushed name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/personalcertvalidityperiod',
          :default => '3',
          :description => 'An optional parameter that specifies the amount of time in years that the default personal certificate is valid',
          :displayname => 'Personal certificate expiration period in years',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/BOOTSTRAP_ADDRESS',
          :default => '2809',
          :description => 'Bootstrap port value (BOOTSTRAP_ADDRESS)',
          :displayname => 'Application sevrver bootstrap address',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9402',
          :description => 'CSIV2 Client Authentication Listener Port (CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS)',
          :displayname => 'Application server CSIV2 Client Authentication Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9403',
          :description => 'CSIV2 Server Authentication Listener Port (CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS)',
          :displayname => 'Application Server CSIV2 Server Authentication Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/DCS_UNICAST_ADDRESS',
          :default => '9353',
          :description => 'High Availability Manager Communication Port (DCS_UNICAST_ADDRESS)',
          :displayname => 'Application Server High Availability Manager Communication Port ',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/IPC_CONNECTOR_ADDRESS',
          :default => '9633',
          :description => 'IPC Connector Port value (IPC_CONNECTOR_ADDRESS)',
          :displayname => 'Application server IPC connector port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/ORB_LISTENER_ADDRESS',
          :default => '9100',
          :description => 'ORB Listener Port (ORB_LISTENER_ADDRESS)',
          :displayname => 'Application Server ORB Listener Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/OVERLAY_TCP_LISTENER_ADDRESS',
          :default => '11004',
          :description => 'Administration Overlay TCP Port (OVERLAY_TCP_LISTENER_ADDRESS)',
          :displayname => 'Application Server Administration Overlay TCP Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/OVERLAY_UDP_LISTENER_ADDRESS',
          :default => '11003',
          :description => 'Administration Overlay UDP Port (OVERLAY_UDP_LISTENER_ADDRESS)',
          :displayname => 'Application Server Administration Overlay UDP Port ',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9401',
          :description => 'Application Server SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'Application Server SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_ENDPOINT_ADDRESS',
          :default => '7276',
          :description => 'Service Integration Port (SIB_ENDPOINT_ADDRESS)',
          :displayname => 'Application Server Service Integration Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_ENDPOINT_SECURE_ADDRESS',
          :default => '7286',
          :description => 'Service Integration Secure Port  (SIB_ENDPOINT_SECURE_ADDRESS)',
          :displayname => 'Application Server Service Integration Secure Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_MQ_ENDPOINT_ADDRESS',
          :default => '5558',
          :description => 'MQ Transport Port (SIB_MQ_ENDPOINT_ADDRESS)',
          :displayname => 'Application Server MQ Transport Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_MQ_ENDPOINT_SECURE_ADDRESS',
          :default => '5578',
          :description => 'MQ Transport Secure Port  (SIB_MQ_ENDPOINT_SECURE_ADDRESS)',
          :displayname => 'Application Server MQ Transport Secure Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIP_DEFAULTHOST',
          :default => '5060',
          :description => 'SIP Container Port (SIP_DEFAULTHOST)',
          :displayname => 'Application Server SIP Container Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIP_DEFAULTHOST_SECURE',
          :default => '5061',
          :description => 'SIP Container Secure Port (SIP_DEFAULTHOST_SECURE)',
          :displayname => 'Application Server SIP Container Secure Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8880',
          :description => 'SOAP connector port value (SOAP_CONNECTOR_ADDRESS)',
          :displayname => 'Application server SOAP connector port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_adminhost',
          :default => '9060',
          :description => 'Server administrative console port (WC_adminhost)',
          :displayname => 'Administrative console port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_adminhost_secure',
          :default => '9043',
          :description => 'Server adminsitrative secure console port (WC_adminhost_secure)',
          :displayname => 'Administrative Console Secure Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_defaulthost',
          :default => '9080',
          :description => 'HTTP Transport port (WC_defaulthost)',
          :displayname => 'Application server HTTP Transport Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_defaulthost_secure',
          :default => '9443',
          :description => 'HTTP Transport Secure Port (WC_defaulthost_secure)',
          :displayname => 'Application server Secure HTTP Transport Port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/profile',
          :default => 'AppSrv01',
          :description => 'Application server profile name',
          :displayname => 'Application server profile name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/server',
          :default => 'server01',
          :description => 'Name of the application server',
          :displayname => 'Application server name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/signingcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the root signing certificate that you create when you create the profile',
          :displayname => 'Root certificate distinguished name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/signingcertvalidityperiod',
          :default => '15',
          :description => 'An optional parameter that specifies the amount of time in years that the root signing certificate is valid',
          :displayname => 'Root signing certificate expiration period in years',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/security/admin_user',
          :default => 'wasadmin',
          :description => 'The username for securing the WebSphere adminstrative console',
          :displayname => 'WebSphere administrative user name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/security/admin_user_pwd',
          :default => '',
          :description => 'The password for the WebSphere administrative account',
          :displayname => 'WebSphere administrative user password',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/unmanaged_node/unmngNode01/host_name',
          :default => '',
          :description => 'The host name or ipaddress of the unmanaged host',
          :displayname => 'Unmanaged host name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/unmanaged_node/unmngNode01/node_name',
          :default => '{SHORTHOSTNAME}UnmangedNode01',
          :description => 'Node name for the unmanaged node',
          :displayname => 'Unmanaged node name ',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/unmanaged_node/unmngNode01/os',
          :default => 'linux',
          :description => 'Indicates the operating system type for the unmanaged node',
          :displayname => 'Unmanaged node operating system type',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/version',
          :default => '9.0.0.2',
          :description => 'The release and fixpack level of WebSphere Application Server to be installed. Example formats are 8.5.5.11 or 9.0.0.4',
          :displayname => 'WebSphere Application Server version',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/admin_port',
          :default => '8008',
          :description => 'IBM HTTP administrative server port.  Used for creating the web server definition',
          :displayname => 'IBM HTTP administrative server port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/ihs_admin_password',
          :default => '',
          :description => 'IBM HTTP administrative username password. Used for creating the web server definition ',
          :displayname => 'IBM HTTP administrative username password',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/ihs_admin_user',
          :default => '',
          :description => 'IBM HTTP administrative username. Used for creating the web server definition',
          :displayname => 'IBM HTTP administrative username',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/install_dir',
          :default => '/opt/IBM/HTTPServer',
          :description => 'Specify the HTTP Server installation directory. Used for creating the web server definition',
          :displayname => 'IBM HTTP Server installation directory',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/node_name',
          :default => '{SHORTHOSTNAME}UnmangedNode01',
          :description => 'Web server node name',
          :displayname => 'was webserver ihs_server node_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/plugin_dir',
          :default => '/opt/IBM/WebSphere/Plugins',
          :description => 'Specify the webserver plugin directory. Used for creating the web server definition',
          :displayname => 'WebSphere plugin installation directory',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/webapp_mapping',
          :default => 'ALL',
          :description => 'Indicate how the applications should be mapped from the webserver',
          :displayname => 'Map all applications to the webserver',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/webserver_name',
          :default => 'webserver1',
          :description => 'Web server server name',
          :displayname => 'was webserver ihs_server webserver_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/webserver_port',
          :default => '80',
          :description => 'HTTP Server listener port that will receive requests on. Use for creating the web server definition',
          :displayname => 'IBM HTTP server listener port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/webserver_type',
          :default => 'IHS',
          :description => 'HTTP Server vendor.  Example IHS',
          :displayname => 'Type of WebServer',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/clusters/cluster01/cluster_name',
          :default => 'cluster01',
          :description => 'Name of the cluster that will be created',
          :displayname => 'WebSphere Cluster name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/clusters/cluster01/cluster_servers/cluster_server01/server_name',
          :default => 'server01',
          :description => 'Name of the cluster member that will created on each of the nodes',
          :displayname => 'WebSphere Cluster member name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/clusters/cluster01/session_rep',
          :default => 'true ',
          :description => 'was wsadmin clusters cluster01 session_rep',
          :displayname => 'was wsadmin clusters cluster01 session_rep',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/node_name',
          :default => '{SHORTHOSTNAME}CellManager01',
          :description => 'Node for the deployment manager that will be updated',
          :displayname => 'Deployment manager node name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/profile_path',
          :default => '',
          :description => 'Directoy where the deployment manager profile resides',
          :displayname => 'Deployment manager profile path',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/property_value_initial',
          :default => '256',
          :description => 'Minimum JVM heap size',
          :displayname => 'Deployment manager minimum JVM Heap Size',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/property_value_maximum',
          :default => '512',
          :description => 'Maximum JVM heap size',
          :displayname => 'Deployment manager maximum JVM Heap Size',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/server_name',
          :default => 'dmgr',
          :description => 'Name of server that will be updated for JVM heap size',
          :displayname => 'Deployment Manager server name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/node_name',
          :default => '',
          :description => 'Node for the node agent that will be updated',
          :displayname => 'Node agent node name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/profile_path',
          :default => '',
          :description => 'Node agent directory where the profile resides',
          :displayname => 'Node agent profile path',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/property_value_initial',
          :default => '256',
          :description => 'Minimum JVM heap size',
          :displayname => 'Node agent minimum JVM Heap Size',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/property_value_maximum',
          :default => '512',
          :description => 'Maximum JVM heap size',
          :displayname => 'Node agent maximum JVM heap size',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/server_name',
          :default => 'nodeagent',
          :description => 'Name of server that will be updated for JVM heap size',
          :displayname => 'Node agent server name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/node_name',
          :default => '',
          :description => 'Node for the application server that will be updated',
          :displayname => 'Application server node name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/profile_path',
          :default => '',
          :description => 'Directoy where the application server profile resides',
          :displayname => 'Application server profile path',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/property_value_initial',
          :default => '256',
          :description => 'Minimum JVM heap size',
          :displayname => 'Application server minimum JVM Heap Size',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/property_value_maximum',
          :default => '512',
          :description => 'Maximum JVM heap size',
          :displayname => 'Application server maximum JVM Heap Size',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/server_name',
          :default => '',
          :description => 'Name of server that will be updated for JVM heap size',
          :displayname => 'Application server name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
recipe 'was::cleanup.rb', '
Cleanup Post WebSphere Install
'
recipe 'was::configure_dmgr.rb', '
Configure Deployment Manager JVM min and max HeapSize.
'
recipe 'was::configure_nodeagent.rb', '
Configure Node agent JVM min and max HeapSize settings
'
recipe 'was::configure_standalone.rb', '
Configure Websphere standalone server JVM min and max HeapSize. 
'
recipe 'was::create_cluster.rb', '
Creates a WebSphere cluster for a given cell.  There is no retry logic if system management throws an exception. 
'
recipe 'was::create_clustermember.rb', '
Create Websphere cluster members/servers
'
recipe 'was::create_dmgr.rb', '
Creates WebSphere Deployment Manager profile and starts the deployment manager. 
'
recipe 'was::create_job_manager.rb', '
Create WebSphere Job Manager profile and starts the job manager. 
'
recipe 'was::create_managed.rb', '
Create node agent, manage node profile, start the node agent
'
recipe 'was::create_standalone.rb', '
Create Websphere standalone server profile and starts the server. 
'
recipe 'was::gather_evidence.rb', '
Gather evidence that installation was successful
'
recipe 'was::install.rb', '
Installs WebSphere Application Server V8.5.5 or V9
'
recipe 'was::prereq.rb', '
This recipe will add to the environment the necessary Pre-Requisites to be added prior ro WebSphere Instalation, this will include
Adding users, Packages, Kernel Configuration
'
recipe 'was::prereq_check.rb', '
This recipe will check the environment prior to installing software.
'
recipe 'was::start_clustermember.rb', '
Start the Websphere cluster members/application servers
'
recipe 'was::unmanaged_webserver.rb', '
Creates a IBM HTTP webserver server defintion as an unmanaged node. 
'
