name             'was'
maintainer       'IBM Corp'
maintainer_email ''
license 'Copyright IBM Corp. 2016, 2017'
description      'Installs/Configures WebSphere Application Server'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.20'
depends          'ibm_cloud_utils'
depends          'im'
depends          'linux'
attribute 'was/config/enable_admin_security',
          :default => 'true',
          :description => 'was enable_admin_security',
          :displayname => 'was enable_admin_security',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/config/os_service',
          :default => 'true',
          :description => 'was os_service',
          :displayname => 'was os_service',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/config/use_default_certs',
          :default => 'true',
          :description => 'was use_default_certs',
          :displayname => 'was use_default_certs',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/dmgr_host_name',
          :default => '',
          :description => 'was dmgr_host_name',
          :displayname => 'was dmgr_host_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/dmgr_role_name',
          :default => '',
          :description => 'dmgr_role_name',
          :displayname => 'dmgr_role_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/edition/base',
          :default => 'false',
          :description => 'WebSphere base edition',
          :displayname => 'WebSphere base edition',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/edition/nd',
          :default => 'true',
          :description => 'WebSphere nd edition',
          :displayname => 'WebSphere nd edition',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/features/core.feature',
          :default => 'true',
          :description => 'WebSphere features core.feature',
          :displayname => 'WebSphere features core.feature',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/features/ejbdeploy',
          :default => 'true',
          :description => 'WebSphere features ejbdeploy',
          :displayname => 'WebSphere features ejbdeploy',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/features/embeddablecontainer',
          :default => 'true',
          :description => 'WebSphere features embeddablecontainer',
          :displayname => 'WebSphere features embeddablecontainer',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/features/liberty',
          :default => 'false',
          :description => 'WebSphere features liberty',
          :displayname => 'WebSphere features liberty',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/features/samples',
          :default => 'false',
          :description => 'WebSphere features samples',
          :displayname => 'WebSphere features samples',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/features/thinclient',
          :default => 'true',
          :description => 'WebSphere features thinclient',
          :displayname => 'WebSphere features thinclient',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/ihs_host_name',
          :default => '',
          :description => 'was ihs_host_name',
          :displayname => 'was ihs_host_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/ihs_role_names',
          :default => '',
          :description => 'ihs_role_names',
          :displayname => 'ihs_role_names',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'array'
attribute 'was/install_dir',
          :default => '/opt/IBM/WebSphere/AppServer',
          :description => 'WebSphere install_dir',
          :displayname => 'WebSphere install_dir',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/java_features/websphere_java_v8/enable',
          :default => 'true',
          :description => 'WebSphere java_features websphere_java_v8 enable',
          :displayname => 'WebSphere java_features websphere_java_v8 enable',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/java_features/websphere_java_v8/offering_id',
          :default => 'com.ibm.java.jdk.v8',
          :description => 'WebSphere java_features websphere_java_v8 offering_id',
          :displayname => 'WebSphere java_features websphere_java_v8 offering_id',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/java_version',
          :default => '8.0.4.10',
          :description => 'WebSphere nd java_version',
          :displayname => 'WebSphere nd java_version',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/os_perms',
          :default => '750',
          :description => 'WebSphere os_perms',
          :displayname => 'WebSphere os_perms',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/os_users/was/comment',
          :default => 'WAS administrative user',
          :description => 'was os_users comment',
          :displayname => 'was os_users comment',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/os_users/was/gid',
          :default => 'wasgrp',
          :description => 'was os_users gid',
          :displayname => 'was os_users gid',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/os_users/was/home',
          :default => '/home/wasadmin',
          :description => 'was os_users home',
          :displayname => 'was os_users home',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/os_users/was/ldap_user',
          :default => 'false',
          :description => 'was ldap_user',
          :displayname => 'was ldap_user',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/os_users/was/name',
          :default => 'wasadmin',
          :description => 'was os_users name',
          :displayname => 'was os_users name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/os_users/was/shell',
          :default => '/bin/bash',
          :description => 'was os_users shell',
          :displayname => 'was os_users shell',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profile_dir',
          :default => '/opt/IBM/WebSphere/AppServer/profiles',
          :description => 'WebSphere profile_dir',
          :displayname => 'WebSphere profile_dir',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/cell',
          :default => 'cell01',
          :description => 'was dmgr profiles cell',
          :displayname => 'was dmgr profiles cell',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/host',
          :default => '',
          :description => 'was dmgr profiles host',
          :displayname => 'was dmgr profiles host',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/keystorepassword',
          :default => '',
          :description => 'was dmgr profiles keystorepassword',
          :displayname => 'was dmgr profiles keystorepassword',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/node',
          :default => '{SHORTHOSTNAME}CellManager01',
          :description => 'was dmgr profiles node',
          :displayname => 'was dmgr profiles node',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/personalcertdn',
          :default => '',
          :description => 'was dmgr profiles personalcertdn',
          :displayname => 'was dmgr profiles personalcertdn',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/personalcertvalidityperiod',
          :default => '3',
          :description => 'was dmgr profiles personalcertvalidityperiod',
          :displayname => 'was dmgr profiles personalcertvalidityperiod',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/BOOTSTRAP_ADDRESS',
          :default => '9809',
          :description => 'was dmgr profiles ports BOOTSTRAP_ADDRESS',
          :displayname => 'was dmgr profiles ports BOOTSTRAP_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/CELL_DISCOVERY_ADDRESS',
          :default => '7277',
          :description => 'was dmgr profiles ports CELL_DISCOVERY_ADDRESS',
          :displayname => 'was dmgr profiles ports CELL_DISCOVERY_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9402',
          :description => 'was dmgr profiles ports CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :displayname => 'was dmgr profiles ports CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9403',
          :description => 'was dmgr profiles ports CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'was dmgr profiles ports CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/DCS_UNICAST_ADDRESS',
          :default => '9352',
          :description => 'was dmgr profiles ports DCS_UNICAST_ADDRESS',
          :displayname => 'was dmgr profiles ports DCS_UNICAST_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/DataPowerMgr_inbound_secure',
          :default => '5555',
          :description => 'was dmgr profiles ports DataPowerMgr_inbound_secure',
          :displayname => 'was dmgr profiles ports DataPowerMgr_inbound_secure',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/IPC_CONNECTOR_ADDRESS',
          :default => '9632',
          :description => 'was dmgr profiles ports IPC_CONNECTOR_ADDRESS',
          :displayname => 'was dmgr profiles ports IPC_CONNECTOR_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/ORB_LISTENER_ADDRESS',
          :default => '9100',
          :description => 'was dmgr profiles ports ORB_LISTENER_ADDRESS',
          :displayname => 'was dmgr profiles ports ORB_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/OVERLAY_TCP_LISTENER_ADDRESS',
          :default => '11006',
          :description => 'was dmgr profiles ports OVERLAY_TCP_LISTENER_ADDRESS',
          :displayname => 'was dmgr profiles ports OVERLAY_TCP_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/OVERLAY_UDP_LISTENER_ADDRESS',
          :default => '11005',
          :description => 'was dmgr profiles ports OVERLAY_UDP_LISTENER_ADDRESS',
          :displayname => 'was dmgr profiles ports OVERLAY_UDP_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9401',
          :description => 'was dmgr profiles ports SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'was dmgr profiles ports SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8879',
          :description => 'was dmgr profiles ports SOAP_CONNECTOR_ADDRESS',
          :displayname => 'was dmgr profiles ports SOAP_CONNECTOR_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/STATUS_LISTENER_ADDRESS',
          :default => '9420',
          :description => 'was dmgr profiles ports STATUS_LISTENER_ADDRESS',
          :displayname => 'was dmgr profiles ports STATUS_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/WC_adminhost',
          :default => '9060',
          :description => 'was dmgr profiles ports WC_adminhost',
          :displayname => 'was dmgr profiles ports WC_adminhost',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/WC_adminhost_secure',
          :default => '9043',
          :description => 'was dmgr profiles ports WC_adminhost_secure',
          :displayname => 'was dmgr profiles ports WC_adminhost_secure',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/XDAGENT_PORT',
          :default => '7060',
          :description => 'was dmgr profiles ports XDAGENT_PORT',
          :displayname => 'was dmgr profiles ports XDAGENT_PORT',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/profile',
          :default => 'Dmgr01',
          :description => 'was dmgr profiles profile',
          :displayname => 'was dmgr profiles profile',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/signingcertdn',
          :default => '',
          :description => 'was dmgr profiles signingcertdn',
          :displayname => 'was dmgr profiles signingcertdn',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/dmgr/signingcertvalidityperiod',
          :default => '15',
          :description => 'was dmgr profiles signingcertvalidityperiod',
          :displayname => 'was dmgr profiles signingcertvalidityperiod',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/cell',
          :default => 'cell01',
          :description => 'was job_manager profiles cell',
          :displayname => 'was job_manager profiles cell',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/host',
          :default => '{FULLHOSTNAME}',
          :description => 'was job_manager profiles host',
          :displayname => 'was job_manager profiles host',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/keystorepassword',
          :default => '',
          :description => 'was job_manager profiles keystorepassword',
          :displayname => 'was job_manager profiles keystorepassword',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/node',
          :default => '{SHORTHOSTNAME}JobMgr01',
          :description => 'was job_manager profiles node',
          :displayname => 'was job_manager profiles node',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/personalcertdn',
          :default => '',
          :description => 'was job_manager profiles personalcertdn',
          :displayname => 'was job_manager profiles personalcertdn',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/personalcertvalidityperiod',
          :default => '3',
          :description => 'was job_manager profiles personalcertvalidityperiod',
          :displayname => 'was job_manager profiles personalcertvalidityperiod',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/BOOTSTRAP_ADDRESS',
          :default => '9808',
          :description => 'was job_manager profiles ports BOOTSTRAP_ADDRESS',
          :displayname => 'was job_manager profiles ports BOOTSTRAP_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9402',
          :description => 'was job_manager profiles ports CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :displayname => 'was job_manager profiles ports CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9403',
          :description => 'was job_manager profiles ports CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'was job_manager profiles ports CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/IPC_CONNECTOR_ADDRESS',
          :default => '9631',
          :description => 'was job_manager profiles ports IPC_CONNECTOR_ADDRESS',
          :displayname => 'was job_manager profiles ports IPC_CONNECTOR_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/ORB_LISTENER_ADDRESS',
          :default => '9099',
          :description => 'was job_manager profiles ports ORB_LISTENER_ADDRESS',
          :displayname => 'was job_manager profiles ports ORB_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9401',
          :description => 'was job_manager profiles ports SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'was job_manager profiles ports SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8876',
          :description => 'was job_manager profiles ports SOAP_CONNECTOR_ADDRESS',
          :displayname => 'was job_manager profiles ports SOAP_CONNECTOR_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/STATUS_LISTENER_ADDRESS',
          :default => '9425',
          :description => 'was job_manager profiles ports STATUS_LISTENER_ADDRESS',
          :displayname => 'was job_manager profiles ports STATUS_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/WC_adminhost',
          :default => '9960',
          :description => 'was job_manager profiles ports WC_adminhost',
          :displayname => 'was job_manager profiles ports WC_adminhost',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/WC_adminhost_secure',
          :default => '9943',
          :description => 'was job_manager profiles ports WC_adminhost_secure',
          :displayname => 'was job_manager profiles ports WC_adminhost_secure',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/profile',
          :default => 'JobMgr01',
          :description => 'was job_manager profiles profile',
          :displayname => 'was job_manager profiles profile',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/signingcertdn',
          :default => '',
          :description => 'was job_manager profiles signingcertdn',
          :displayname => 'was job_manager profiles signingcertdn',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/job_manager/signingcertvalidityperiod',
          :default => '15',
          :description => 'was job_manager profiles signingcertvalidityperiod',
          :displayname => 'was job_manager profiles signingcertvalidityperiod',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/dmgr_host',
          :default => '',
          :description => 'was node_profile profiles dmgr_host',
          :displayname => 'was node_profile profiles dmgr_host',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/dmgr_port',
          :default => '',
          :description => 'was node_profile profiles dmgr_port',
          :displayname => 'was node_profile profiles dmgr_port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/host',
          :default => '',
          :description => 'was node_profile profiles host',
          :displayname => 'was node_profile profiles host',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/keystorepassword',
          :default => '',
          :description => 'was node_profile profiles keystorepassword',
          :displayname => 'was node_profile profiles keystorepassword',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/node',
          :default => '{SHORTHOSTNAME}Node01',
          :description => 'was node_profile profiles node',
          :displayname => 'was node_profile profiles node',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/personalcertdn',
          :default => '',
          :description => 'was node_profile profiles personalcertdn',
          :displayname => 'was node_profile profiles personalcertdn',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/personalcertvalidityperiod',
          :default => '3',
          :description => 'was node_profile profiles personalcertvalidityperiod',
          :displayname => 'was node_profile profiles personalcertvalidityperiod',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/BOOTSTRAP_ADDRESS',
          :default => '2810',
          :description => 'was node_profile profiles ports BOOTSTRAP_ADDRESS',
          :displayname => 'was node_profile profiles ports BOOTSTRAP_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9202',
          :description => 'was node_profile profiles ports CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :displayname => 'was node_profile profiles ports CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9201',
          :description => 'was node_profile profiles ports CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'was node_profile profiles ports CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/DCS_UNICAST_ADDRESS',
          :default => '9354',
          :description => 'was node_profile profiles ports DCS_UNICAST_ADDRESS',
          :displayname => 'was node_profile profiles ports DCS_UNICAST_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/IPC_CONNECTOR_ADDRESS',
          :default => '9626',
          :description => 'was node_profile profiles ports IPC_CONNECTOR_ADDRESS',
          :displayname => 'was node_profile profiles ports IPC_CONNECTOR_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/NODE_DISCOVERY_ADDRESS',
          :default => '7272',
          :description => 'was node_profile profiles ports NODE_DISCOVERY_ADDRESS',
          :displayname => 'was node_profile profiles ports NODE_DISCOVERY_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/NODE_IPV6_MULTICAST_DISCOVERY_ADDRESS',
          :default => '5001',
          :description => 'was node_profile profiles ports NODE_IPV6_MULTICAST_DISCOVERY_ADDRESS',
          :displayname => 'was node_profile profiles ports NODE_IPV6_MULTICAST_DISCOVERY_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/NODE_MULTICAST_DISCOVERY_ADDRESS',
          :default => '5000',
          :description => 'was node_profile profiles ports NODE_MULTICAST_DISCOVERY_ADDRESS',
          :displayname => 'was node_profile profiles ports NODE_MULTICAST_DISCOVERY_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/ORB_LISTENER_ADDRESS',
          :default => '9101',
          :description => 'was node_profile profiles ports ORB_LISTENER_ADDRESS',
          :displayname => 'was node_profile profiles ports ORB_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/OVERLAY_TCP_LISTENER_ADDRESS',
          :default => '11002',
          :description => 'was node_profile profiles ports OVERLAY_TCP_LISTENER_ADDRESS',
          :displayname => 'was node_profile profiles ports OVERLAY_TCP_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/OVERLAY_UDP_LISTENER_ADDRESS',
          :default => '11001',
          :description => 'was node_profile profiles ports OVERLAY_UDP_LISTENER_ADDRESS',
          :displayname => 'was node_profile profiles ports OVERLAY_UDP_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9901',
          :description => 'was node_profile profiles ports SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'was node_profile profiles ports SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8878',
          :description => 'was node_profile profiles ports SOAP_CONNECTOR_ADDRESS',
          :displayname => 'was node_profile profiles ports SOAP_CONNECTOR_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/STATUS_LISTENER_ADDRESS',
          :default => '9420',
          :description => 'was node_profile profiles ports STATUS_LISTENER_ADDRESS',
          :displayname => 'was node_profile profiles ports STATUS_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/WC_adminhost',
          :default => '9060',
          :description => 'was node_profile profiles ports WC_adminhost',
          :displayname => 'was node_profile profiles ports WC_adminhost',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/XDAGENT_PORT',
          :default => '7061',
          :description => 'was node_profile profiles ports XDAGENT_PORT',
          :displayname => 'was node_profile profiles ports XDAGENT_PORT',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/profile',
          :default => 'AppSrv01',
          :description => 'was node_profile profiles profile',
          :displayname => 'was node_profile profiles profile',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/signingcertdn',
          :default => '',
          :description => 'was node_profile profiles signingcertdn',
          :displayname => 'was node_profile profiles signingcertdn',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/node_profile/signingcertvalidityperiod',
          :default => '15',
          :description => 'was node_profile profiles signingcertvalidityperiod',
          :displayname => 'was node_profile profiles signingcertvalidityperiod',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/cell',
          :default => 'cell01',
          :description => 'was standalone_profiles profiles cell',
          :displayname => 'was standalone_profiles profiles cell',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/host',
          :default => '{FULLHOSTNAME}',
          :description => 'was standalone_profiles profiles host',
          :displayname => 'was standalone_profiles profiles host',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/keystorepassword',
          :default => '',
          :description => 'was standalone_profiles profiles keystorepassword',
          :displayname => 'was standalone_profiles profiles keystorepassword',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/node',
          :default => '{SHORTHOSTNAME}Node01',
          :description => 'was standalone_profiles profiles node',
          :displayname => 'was standalone_profiles profiles node',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/personalcertdn',
          :default => '',
          :description => 'was standalone_profiles profiles personalcertdn',
          :displayname => 'was standalone_profiles profiles personalcertdn',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/personalcertvalidityperiod',
          :default => '3',
          :description => 'was standalone_profiles profiles personalcertvalidityperiod',
          :displayname => 'was standalone_profiles profiles personalcertvalidityperiod',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/BOOTSTRAP_ADDRESS',
          :default => '2809',
          :description => 'was standalone_profiles profiles ports BOOTSTRAP_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports BOOTSTRAP_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9402',
          :description => 'was standalone_profiles profiles ports CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9403',
          :description => 'was standalone_profiles profiles ports CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/DCS_UNICAST_ADDRESS',
          :default => '9353',
          :description => 'was standalone_profiles profiles ports DCS_UNICAST_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports DCS_UNICAST_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/IPC_CONNECTOR_ADDRESS',
          :default => '9633',
          :description => 'was standalone_profiles profiles ports IPC_CONNECTOR_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports IPC_CONNECTOR_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/ORB_LISTENER_ADDRESS',
          :default => '9100',
          :description => 'was standalone_profiles profiles ports ORB_LISTENER_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports ORB_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/OVERLAY_TCP_LISTENER_ADDRESS',
          :default => '11004',
          :description => 'was standalone_profiles profiles ports OVERLAY_TCP_LISTENER_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports OVERLAY_TCP_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/OVERLAY_UDP_LISTENER_ADDRESS',
          :default => '11003',
          :description => 'was standalone_profiles profiles ports OVERLAY_UDP_LISTENER_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports OVERLAY_UDP_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9401',
          :description => 'was standalone_profiles profiles ports SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_ENDPOINT_ADDRESS',
          :default => '7276',
          :description => 'was standalone_profiles profiles ports SIB_ENDPOINT_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports SIB_ENDPOINT_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_ENDPOINT_SECURE_ADDRESS',
          :default => '7286',
          :description => 'was standalone_profiles profiles ports SIB_ENDPOINT_SECURE_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports SIB_ENDPOINT_SECURE_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_MQ_ENDPOINT_ADDRESS',
          :default => '5558',
          :description => 'was standalone_profiles profiles ports SIB_MQ_ENDPOINT_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports SIB_MQ_ENDPOINT_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_MQ_ENDPOINT_SECURE_ADDRESS',
          :default => '5578',
          :description => 'was standalone_profiles profiles ports SIB_MQ_ENDPOINT_SECURE_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports SIB_MQ_ENDPOINT_SECURE_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIP_DEFAULTHOST',
          :default => '5060',
          :description => 'was standalone_profiles profiles ports SIP_DEFAULTHOST',
          :displayname => 'was standalone_profiles profiles ports SIP_DEFAULTHOST',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIP_DEFAULTHOST_SECURE',
          :default => '5061',
          :description => 'was standalone_profiles profiles ports SIP_DEFAULTHOST_SECURE',
          :displayname => 'was standalone_profiles profiles ports SIP_DEFAULTHOST_SECURE',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8880',
          :description => 'was standalone_profiles profiles ports SOAP_CONNECTOR_ADDRESS',
          :displayname => 'was standalone_profiles profiles ports SOAP_CONNECTOR_ADDRESS',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_adminhost',
          :default => '9060',
          :description => 'was standalone_profiles profiles ports WC_adminhost',
          :displayname => 'was standalone_profiles profiles ports WC_adminhost',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_adminhost_secure',
          :default => '9043',
          :description => 'was standalone_profiles profiles ports WC_adminhost_secure',
          :displayname => 'was standalone_profiles profiles ports WC_adminhost_secure',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_defaulthost',
          :default => '9080',
          :description => 'was standalone_profiles profiles ports WC_defaulthost',
          :displayname => 'was standalone_profiles profiles ports WC_defaulthost',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_defaulthost_secure',
          :default => '9443',
          :description => 'was standalone_profiles profiles ports WC_defaulthost_secure',
          :displayname => 'was standalone_profiles profiles ports WC_defaulthost_secure',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/profile',
          :default => 'AppSrv01',
          :description => 'was standalone_profiles profiles profile',
          :displayname => 'was standalone_profiles profiles profile',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/server',
          :default => 'standalone01',
          :description => 'was standalone_profiles profiles server',
          :displayname => 'was standalone_profiles profiles server',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/signingcertdn',
          :default => '',
          :description => 'was standalone_profiles profiles signingcertdn',
          :displayname => 'was standalone_profiles profiles signingcertdn',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/signingcertvalidityperiod',
          :default => '15',
          :description => 'was standalone_profiles profiles signingcertvalidityperiod',
          :displayname => 'was standalone_profiles profiles signingcertvalidityperiod',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/security/admin_user',
          :default => 'wasadmin',
          :description => 'was administrative user',
          :displayname => 'was admin user',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/security/admin_user_pwd',
          :default => '',
          :description => 'was administrative password',
          :displayname => 'was admin password',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'false',
          :type => 'string'
attribute 'was/unmanaged_node/unmngNode01/host_name',
          :default => '',
          :description => 'was unmanaged_node host_name',
          :displayname => 'was unmanaged_node host_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/unmanaged_node/unmngNode01/node_name',
          :default => '{SHORTHOSTNAME}UnmangedNode01',
          :description => 'was unmanaged_node node_name',
          :displayname => 'was unmanaged_node node_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/unmanaged_node/unmngNode01/os',
          :default => 'linux',
          :description => 'was unmanaged_node os',
          :displayname => 'was unmanaged_node os',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/version',
          :default => '9.0.0.2',
          :description => 'WAS_Version',
          :displayname => 'WAS_Version',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/webserver/ihs_server/admin_port',
          :default => '8008',
          :description => 'was webserver ihs_server admin_port',
          :displayname => 'was webserver ihs_server admin_port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/webserver/ihs_server/ihs_admin_password',
          :default => '',
          :description => 'was webserver ihs_server ihs_admin_password',
          :displayname => 'was webserver ihs_server ihs_admin_password',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'false',
          :type => 'string'
attribute 'was/webserver/ihs_server/ihs_admin_user',
          :default => '',
          :description => 'was webserver ihs_server ihs_admin_user',
          :displayname => 'was webserver ihs_server ihs_admin_user',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/webserver/ihs_server/install_dir',
          :default => '/opt/IBM/HTTPServer',
          :description => 'was webserver ihs_server install_dir',
          :displayname => 'was webserver ihs_server install_dir',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/webserver/ihs_server/node_name',
          :default => '{SHORTHOSTNAME}UnmangedNode01',
          :description => 'was webserver ihs_server node_name',
          :displayname => 'was webserver ihs_server node_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/webserver/ihs_server/plugin_dir',
          :default => '/opt/IBM/WebSphere/Plugins',
          :description => 'was webserver ihs_server plugin_dir',
          :displayname => 'was webserver ihs_server plugin_dir',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/webserver/ihs_server/webapp_mapping',
          :default => 'ALL',
          :description => 'was webserver ihs_server webapp_mapping',
          :displayname => 'was webserver ihs_server webapp_mapping',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/webserver/ihs_server/webserver_name',
          :default => 'webserver1',
          :description => 'was webserver ihs_server webserver_name',
          :displayname => 'was webserver ihs_server webserver_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/webserver/ihs_server/webserver_port',
          :default => '80',
          :description => 'was webserver ihs_server webserver_port',
          :displayname => 'was webserver ihs_server webserver_port',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/webserver/ihs_server/webserver_type',
          :default => 'IHS',
          :description => 'was webserver ihs_server webserver_type',
          :displayname => 'was webserver ihs_server webserver_type',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/clusters/cluster01/cluster_name',
          :default => 'cluster01',
          :description => 'was clusters cluster_name',
          :displayname => 'was clusters cluster_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/clusters/cluster01/cluster_servers/cluster_server01/server_name',
          :default => 'server01',
          :description => 'was cluster_servers server_name',
          :displayname => 'was cluster_servers server_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/clusters/cluster01/session_rep',
          :default => 'true ',
          :description => 'was wsadmin clusters cluster01 session_rep',
          :displayname => 'was wsadmin clusters cluster01 session_rep',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/node_name',
          :default => '{SHORTHOSTNAME}CellManager01',
          :description => 'was wsadmin dmgr jvmproperty node_name',
          :displayname => 'was wsadmin dmgr jvmproperty node_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/profile_path',
          :default => '',
          :description => 'was wsadmin dmgr jvmproperty profile_path',
          :displayname => 'was wsadmin dmgr jvmproperty profile_path',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/property_value_initial',
          :default => '256',
          :description => 'was wsadmin dmgr jvmproperty property_value_initial',
          :displayname => 'was wsadmin dmgr jvmproperty property_value_initial',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/property_value_maximum',
          :default => '512',
          :description => 'was wsadmin dmgr jvmproperty property_value_maximum',
          :displayname => 'was wsadmin dmgr jvmproperty property_value_maximum',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/server_name',
          :default => 'dmgr',
          :description => 'was wsadmin dmgr jvmproperty server_name',
          :displayname => 'was wsadmin dmgr jvmproperty server_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/node_name',
          :default => '',
          :description => 'was wsadmin nodeagent jvmproperty node_name',
          :displayname => 'was wsadmin nodeagent jvmproperty node_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/profile_path',
          :default => '',
          :description => 'was wsadmin nodeagent jvmproperty profile_path',
          :displayname => 'was wsadmin nodeagent jvmproperty profile_path',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/property_value_initial',
          :default => '256',
          :description => 'was wsadmin nodeagent jvmproperty property_value_initial',
          :displayname => 'was wsadmin nodeagent jvmproperty property_value_initial',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/property_value_maximum',
          :default => '512',
          :description => 'was wsadmin nodeagent jvmproperty property_value_maximum',
          :displayname => 'was wsadmin nodeagent jvmproperty property_value_maximum',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/server_name',
          :default => 'nodeagent',
          :description => 'was wsadmin nodeagent jvmproperty server_name',
          :displayname => 'was wsadmin nodeagent jvmproperty server_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/node_name',
          :default => '',
          :description => 'was wsadmin standalone jvmproperty node_name',
          :displayname => 'was wsadmin standalone jvmproperty node_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/profile_path',
          :default => '',
          :description => 'was wsadmin standalone jvmproperty profile_path',
          :displayname => 'was wsadmin standalone jvmproperty profile_path',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/property_value_initial',
          :default => '256',
          :description => 'was wsadmin standalone jvmproperty property_value_initial',
          :displayname => 'was wsadmin standalone jvmproperty property_value_initial',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/property_value_maximum',
          :default => '512',
          :description => 'was wsadmin standalone jvmproperty property_value_maximum',
          :displayname => 'was wsadmin standalone jvmproperty property_value_maximum',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/server_name',
          :default => '',
          :description => 'was wsadmin standalone jvmproperty server_name',
          :displayname => 'was wsadmin standalone jvmproperty server_name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
recipe 'was::cleanup.rb', '
Cleanup Post WebSphere Install
'
recipe 'was::configure_dmgr.rb', '
Configure Deployment Manager like set the JVM HeapSize min / max etc
'
recipe 'was::configure_nodeagent.rb', '
Configure Node agent like set the JVM HeapSize min / max etc
'
recipe 'was::configure_standalone.rb', '
Configure Websphere standalone server like set the JVM HeapSize min / max etc
'
recipe 'was::create_cluster.rb', '
Create Websphere clusters
'
recipe 'was::create_clustermember.rb', '
Create Websphere cluster members/servers
'
recipe 'was::create_dmgr.rb', '
Create WebSphere Deployment Manager
'
recipe 'was::create_job_manager.rb', '
Create WebSphere Job Manager
'
recipe 'was::create_managed.rb', '
Create node agent, manage node profile, start the node agent
'
recipe 'was::create_standalone.rb', '
Create Websphere standalone server
'
recipe 'was::gather_evidence.rb', '
Gather evidence that installation was successful
'
recipe 'was::install.rb', '
Install WebSphere Application Server
'
recipe 'was::prereq.rb', '
This recipe will add to the environment the necessary Pre-Requisites to be added prior ro WebSphere Instalation, this will include
Adding users, Packages, Kernel Configuration
'
recipe 'was::prereq_check.rb', '
This recipe will check the environment prior to installing software.
'
recipe 'was::start_clustermember.rb', '
Start the Websphere cluster members/application servers
'
recipe 'was::unmanaged_webserver.rb', '
Create unmanaged node, create and configure webserver
'
